@extends('layouts.app')

@section('content')
    <h1>Edit Report</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('reports.update', $report->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="report_type">Report Type</label>
            <input type="text" name="report_type" class="form-control" value="{{ old('report_type', $report->report_type) }}">
        </div>
        <div class="form-group">
            <label for="generated_by">Generated By</label>
            <input type="number" name="generated_by" class="form-control" value="{{ old('generated_by', $report->generated_by) }}">
        </div>
        <div class="form-group">
            <label for="date_generated">Date Generated</label>
            <input type="date" name="date_generated" class="form-control" value="{{ old('date_generated', $report->date_generated) }}">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@endsection
